SPC_Coopenae/SPC_Coopenae.UI/Models/TipoCambio.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SPC_Coopenae.UI.Models
{
    public class TipoCambio
    {
        public int IdTipoCambio { get; set; }

        [Required(ErrorMessage = "El campo código de vendedor es requerido")]
        public decimal Valor { get; set; }

        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM/yyyy}")]
        [Required(ErrorMessage = "El campo código de vendedor es requerido")]
        public DateTime Fecha { get; set; }

        [Required(ErrorMessage = "El campo código de vendedor es requerido")]
        public bool Estado { get; set; } = true;
    }
}

SPC_Coopenae/SPC_Coopenae.UI/Controllers/TipoCambioController.cs
using AutoMapper;
using SPC_Coopenae.DAL.Interfaces;
using SPC_Coopenae.DAL.Metodos;
using SPC_Coopenae.DATA;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SPC_Coopenae.UI.Controllers
{
    public class TipoCambioController : Controller
    {
        ITipoCambioRepositorio _repositorioTipoCambio;

        public TipoCambioController()
        {
            _repositorioTipoCambio = new MTipoCambioRepositorio();
        }

        // GET: TipoCambio
        public ActionResult Index()
        {

            try
            {
                var listado = _repositorioTipoCambio.ListarTipoCambio();
                var listadoMostrar = Mapper.Map<List<Models.TipoCambio>>(listado);
                return View(listadoMostrar);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "Ocurrió un error: " + ex.Message);
                return View();
            }

        }

        [HttpPost]
        public ActionResult GuardarTipoCambio(decimal valor, DateTime fecha)
        {
            try
            {
                var tipoCambio = new Models.TipoCambio
                {
                    Valor = valor,
                    Fecha = fecha,
                    Estado = true
                };

                var tipoCambioMostrar = Mapper.Map<DATA.TipoCambio>(tipoCambio);
                _repositorioTipoCambio.InsertarTipoCambio(tipoCambioMostrar);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "Ocurrió un error: " + ex.Message);
                return View();
            }

        }



    }
}

SPC_Coopenae/SPC_Coopenae.UI/Views/TipoCambio/Index.cshtml
@model IEnumerable<SPC_Coopenae.UI.Models.TipoCambio>

@{
    ViewBag.Title = "Index";
}

<h2>Tipo de Cambio</h2>

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <table class="table">
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Valor)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Fecha)
                    </th>
                    <th></th>
                </tr>

                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            ₡@Html.DisplayFor(modelItem => item.Valor)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Fecha)
                        </td>
                    </tr>
                }

            </table>
        </div>


        <div class="col-md-6">
            @using (Html.BeginForm("GuardarTipoCambio", "TipoCambio"))
            {
                <div class="form-group">
                    <input type="number" name="valor" id="valor" placeholder="Valor" class="form-control" required max="10000" min="50" />
                </div>

                <div class="form-group" id="contenedor-fecha">
                    <input type="text" class="form-control" id="fecha" name="fecha" placeholder="Fecha" required>
                </div>

                <button type="submit" class="btn btn-primary">Guardar</button>

            }
        </div>

    </div>





</div>


@section Styles {
    <link href="~/Content/bootstrap-datepicker.css" rel="stylesheet" />
}

@section scripts {
    @Scripts.Render("~/bundles/datepicker")
}